### ISSUE TITLE
Addition of pyodbc and a database API

### ISSUE THREAD

**Issue by robertqtk** [Microvellum/Fluid-Designer#22]
Can the latest version of pyodbc and a database API be added to the Site-Packages of the blender python directory? I was able to get pyodbc and SQLAlchemy into my local copy of blender and it works pretty well. I believe there exists some opportunities for integrating Fluid Designer into the Microvellum database. 

At the very least pyodbc needs to added as it has the driver (or mapping for Microsoft ODBC) for accessing Microsoft SQL Server databases.

I've seen some people use databases to drive UI and blender objects on the blender artists forum as well. I've seen examples ranging from a full database to using the shipped SQLLite library to store local information.

**Comment by AndrewPeelMV** [comment]
Yeah it would be a great idea to include that python package. If you create a pull request I would be happy to merge it. Thanks!

**Comment by robertqtk** [comment]
I need permission to add branches / pull requests please. Thank you

**Comment by RyanMDev** [comment]
Merged with commit db80872e7d10721f586743f1d053029923b1da73
