### ISSUE TITLE
return absolute value of 'ZDIM' calculator tab

### ISSUE THREAD

**Issue by robertqtk** [Microvellum/Fluid-Designer#24]
Can you return the absolute value of height of a 'ZDIM' calculator tab? Mirror_Z flips an assembly upside down and changes the height a negative value. If one was to insert a calculator into a Assembly that is Mirror_Z the calc function won't behave as expected. Trying to account for this by passing the VPDIMZ variable will create a circular dependency. 

I think since Mirror_Z is used is used on a large # of products / assemblies having the ability to add a calculator as easily as a base cabinet is significantly less rigid.

This change can be done in fd_prompts.py in the OPS_run_calculators class inside the get_size function.

def get_size(self,tab,obj):
        for child in obj.children:
            if tab.calculator_type == 'XDIM' and child.mv.type == 'VPDIMX':
                return child.location.x
            if tab.calculator_type == 'YDIM' and child.mv.type == 'VPDIMY':
                return child.location.y
            if tab.calculator_type == 'ZDIM' and child.mv.type == 'VPDIMZ':
                return abs(child.location.z)

**Comment by RyanMDev** [comment]
Fixed with commit 4e6e7559ab95a88dc822730744f1331ad922e5dd
