### ISSUE TITLE
Represent door swing for cabinet doors.

### ISSUE THREAD

**Issue by RyanMDev** [Microvellum/Fluid-Designer#40]
**Description:**
Swing lines need to be drawn for cabinet doors.  This can be achieved with the ability to draw dimension objects as single lines.

Development Tasks:
- [x] Modify Dimension class to add ability for dimension objects to be drawn as single lines only (no text, arrows or extension lines)
- [x] Modify OpenGL drawing code to handle drawing of single lines.

**Comment by zohozer** [comment]
Will be great also to have a representation of the doors opening direction from the top view, like in the bellow images:

https://www.thegoodguys.com.au/cs/groups/public/documents/graphic/kitchenfeatures-design-3a.png

http://kitchenanddining.net/wp-content/uploads/2014/05/Kitchen-Layouts.jpg

Also, the wall hanging cabinets needs to have two crossing lines like in this pictures:

https://www.thegoodguys.com.au/cs/groups/public/documents/graphic/kitchenfeatures-design-3a.png

https://s-media-cache-ak0.pinimg.com/236x/02/25/0c/02250c5ff0254945c1bc37269d723e64.jpg

http://akioz.com/wp-content/uploads/2017/02/kitchen-layouts-plans-on-kitchen-within-l-shape-layout-shaped-layouts-7.jpg

**Comment by RyanMDev** [comment]
Thanks @zohozer for the detailed feedback. I have extended the OpenGL drawing code to make  drawing these sorts of things possible. However this functionality still needs to be incorporated into the data of the cabinet library, we will look to implement these two features soon.
