### ISSUE TITLE
FD_GENERAL_OT_properties

### ISSUE THREAD

**Issue by andreimd87** [Microvellum/Fluid-Designer#51]
every time i start blender i get the "search for unknown operator 'FD_GENERAL_OT_properties' " message, even with load fluid designer defaults or blender defaults.

![image](https://cloud.githubusercontent.com/assets/19931241/25667462/38b9de76-302c-11e7-9085-0d3573e7d5ec.png)

**Comment by AndrewPeelMV** [comment]
This was happening because we were trying to assign hotkey commands before we registered the operator. I just moved the registration of the keymaps to after the operators are registered, and the warnings are gone now. Thanks for the info.

**Comment by andreimd87** [comment]
thank you
